"""add unique constraint to match number

Revision ID: 236a88ce960d
Revises: 77a571065a7f
Create Date: 2026-09-11 15:00:34.483011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236a88ce960d'
down_revision: Union[str, Sequence[str], None] = '77a571065a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_session_number', 'matches', ['session_id', 'match_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_session_number', 'matches', type_='unique')
    # ### end Alembic commands ###
