"""add player_id to sessions

Revision ID: 2e2079eb6f9b
Revises: a0be5b6232d2
Create Date: 2026-09-26 12:45:24.870544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2079eb6f9b'
down_revision: Union[str, Sequence[str], None] = 'a0be5b6232d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('player_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'player_id')
    # ### end Alembic commands ###
