"""make post mmr nullable fix fix

Revision ID: 66b8111d5177
Revises: ce63c1365a59
Create Date: 2026-09-16 15:52:03.321957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66b8111d5177"
down_revision: Union[str, Sequence[str], None] = "ce63c1365a59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mmr_records", "post_mmr", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mmr_records", "post_mmr", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
