"""add unique constraint to mmr records

Revision ID: 77a571065a7f
Revises: 2484b64746ae
Create Date: 2026-08-26 15:53:40.374582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a571065a7f'
down_revision: Union[str, Sequence[str], None] = '2484b64746ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_mmr_record_match_player', 'mmr_records', ['match_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mmr_record_match_player', 'mmr_records', type_='unique')
    # ### end Alembic commands ###
